name: profile
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: ^3.7.0
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    flutter_riverpod: ^2.6.1
    hooks_riverpod: ^2.6.1
    riverpod_test: ^0.1.8
    talker_riverpod_logger: ^4.7.1
    loading_animation_widget: ^1.3.0
    flutter_svg: ^2.0.17
    reflect_ui: ^0.0.1
    fluentui_system_icons: ^1.1.273
    cached_network_image: ^3.4.1
    animated_text_kit: ^4.2.3
    font_awesome_flutter: ^10.6.0
    url_launcher: ^6.3.1
    flutter_eval: ^0.7.6
    share_plus: ^10.1.4
    highlight: ^0.7.0
    flutter_highlight: ^0.7.0
    code_text_field: ^1.1.0
    
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
flutter:
    uses-material-design: true


  # To add assets to your application, add an assets section, like this:
    assets:
      - assets/images/
      - assets/svg/
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages